#!/bin/bash

# vim: set fileformat=unix #

prog="$(basename ${0})"
logfile=/cygdrive/c/Wise40/Logs/${prog}.log

function log() {
    echo "$(date --rfc-3339=seconds) $*" >> ${logfile}
}

tops=(
    /cygdrive/c/Wise40/Logs
    /cygdrive/c/Users/${USER}/Documents/ASCOM
)

log ""
log "=== Started ==="
while read dir; do
    log "    Removing \"${dir}\" ..."
    /bin/rm -rf "${dir}"
done < <( find "${tops[@]}" -maxdepth 1 -type d -name '*2???-??-??' -mtime +30 ) 
log "=== Done ==="
